# Generated by Django 4.2.6 on 2024-07-16 15:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_state_available', models.BooleanField(blank=True, default=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('flag', models.ImageField(upload_to='flag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_state_available', models.BooleanField(blank=True, default=True, null=True)),
                ('statename', models.CharField(max_length=100)),
                ('stateslug', models.SlugField(unique=True)),
                ('language', models.CharField(max_length=200)),
                ('population', models.IntegerField()),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='country.countrymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_state_available', models.BooleanField(blank=True, default=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('Country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='country.countrymodel')),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.statemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
