# Generated by Django 4.2.6 on 2024-07-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_rename_country_citymodel_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citymodel',
            old_name='State',
            new_name='state',
        ),
    ]
